### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by Mx772** [dreeveapp/dreeve#2]
```docker compose exec app bin/console app:strava:build-files
Building HTML...
  => Calculating Eddington
  => Calculating activity highlights
  => Calculating weekday stats
  => Calculating daytime stats
  => Calculating monthly stats
  => Calculating best power outputs

In StreamBasedActivityPowerRepository.php line 112:
                    
  Division by zero  
                    

app:strava:build-files
```

https://github.com/robiningelbrecht/strava-statistics/blob/bd030c29d6a8979fc0d7c1068315c752f1b8b30a/src/Domain/Strava/Activity/Stream/StreamBasedActivityPowerRepository.php#L112

I'm assuming weight is empty. Where is it getting weight from? Not seeing any entries in Database. Strava profile has it filled out. (Albeit, filled out semi-recently).

**Comment by Mx772** [comment]
Ah, update - I see the issue. 
In Activity Table under data, it's not reporting my weight in the activity for w/e reason. I imagine editing that field would resolve this.

**Comment by robiningelbrecht** [comment]
@Mx772 did you alter the data manually? If so, there's a bug somewhere, this should be fetched automatically

**Comment by Mx772** [comment]
@robiningelbrecht - Negative, I found the issue was Strava decided not to save my weight. So upon re-saving it; I needed to delete the table and re-run the import so it updates all the entries in the table with weight.

**Comment by robiningelbrecht** [comment]
@Mx772 ok, thanks for the update. I'll fix division by zero bug nonetheless ;). Thanks for the input

**Comment by Mx772** [comment]
If nothing else, could have a setting in the UI to set weight or expose an env variable.

**Comment by robiningelbrecht** [comment]
@Mx772 I could do that. Care to open a separate ticket ;)?
