### ISSUE TITLE
Error AthleteWeigth buildin file

### ISSUE THREAD

**Issue by cfjuan** [dreeveapp/dreeve#23]
After upgrade ,  when I try to built file, this error occurrs :

Building HTML...
  => Calculating Eddington
  => Calculating activity highlights
  => Calculating weekday stats
  => Calculating daytime stats
  => Calculating monthly stats
  => Calculating best power outputs
In DbalAthleteWeightRepository.php line 46:
                                                          
  AthleteWeight for date "2015-04-18 00:00:00" not found

**Comment by robiningelbrecht** [comment]
Since the last update you need to provide an athlete weight. Just like you provide FTP:

```
# History of weight (in kg). Needed to calculate relative w/kg.
ATHLETE_WEIGHTS='{
    "YYYY-MM-DD": 74.6,
    "YYYY-MM-DD": 70.3
}'
```
