### ISSUE TITLE
docker compose exec app bin/console app:strava:build-files fails - In DbalGearRepository.php line 66

### ISSUE THREAD

**Issue by theh0ff** [dreeveapp/dreeve#36]
Hi there,

This project looks good and the import of the data is working for me fine, but the build files part keeps erroring:

```
docker compose exec app bin/console app:strava:build-files
Building HTML...
  => Calculating Eddington
  => Calculating activity highlights
  => Calculating weekday stats
  => Calculating daytime stats
  => Calculating monthly stats
  => Calculating best power outputs
  => Enriching activities with data

In DbalGearRepository.php line 66:

  Gear "gear-b1261650" not found


app:strava:build-files
```

**Comment by robiningelbrecht** [comment]
@theh0ff that's because not all your Strava data has been imported yet. This is also stated in the readme:

> You can only build the files once all data from Strava was imported

**Comment by theh0ff** [comment]
Thanks @robiningelbrecht, I've got a few years of strava activites to import and thought it was done - will keep going.

**Comment by robiningelbrecht** [comment]
@theh0ff yeah Strava has API rate limits unfortunately :(. If it were up to me, everything would be imported in a few minutes, but... it's not up to me.
Can I close this issue? 
I'll make a new issue to have a better error message, saying "Wait until all your Strava data has been imported"

**Comment by theh0ff** [comment]
By all means - please close.
