### ISSUE TITLE
.env should have alternate ftp input

### ISSUE THREAD

**Issue by Mx772** [dreeveapp/dreeve#4]
Currently in the .env file, there is:
```
# History of FTP. Needed to calculate relative w/kg.
FTP_VALUES='{
    "YYYY-MM-DD": 198,
    "YYYY-MM-DD": 220
}'
```

However, it seems basically every service hates this formatting. (I couldn't find a way to do arrays in Portainer, Komodo, etc) 

Not sure on alternatives, but possibly a single string which can be unwrapped like a csv?
```
FTP_VALUE="YYYY-MM-DD,198,YYYY-MM-DD,220"
```

**Comment by robiningelbrecht** [comment]
You can perfectly have the current solution as a one liner:

```
FTP_VALUES='{"YYYY-MM-DD": 198,"YYYY-MM-DD": 220}'
```

It is a string as any other?

**Comment by Mx772** [comment]
Yup, formatting on the separate lines was causing issues. Early morning brain fart.
