### ISSUE TITLE
Import challenges (local file) not importing

### ISSUE THREAD

**Issue by cyclo-x** [dreeveapp/dreeve#44]
File needs to be stored in:
_./storage/files/strava-challenge-history.html_ 

In /var/www/src/Domain/Strava/Strava.php
line 225 and line 228 points to _files/strava-challenge-history.html_ instead of _storage/files/strava-challenge-history.html_

**Comment by robiningelbrecht** [comment]
Indeed! thanks for reporting. Releasing a fix in a few minutes
