### ISSUE TITLE
Provide better reporting on why build-data cannot run

### ISSUE THREAD

**Issue by FoxxMD** [dreeveapp/dreeve#50]
I have just updated to 0.2.1 and run `import-data` to update my database (on an existing, previously fully-imported and working site). It imported 2 activities and finished running without hitting api limits.

Running `build-files` then reports

```
Wait until all Strava data has been imported before building the app
```

without any additional details. It should work since the import finished but I don't know what is missing since the logging doesn't indicate anything.

Please add additional logging so I can troubleshoot what is missing from the import, thank you.

**Comment by robiningelbrecht** [comment]
@FoxxMD I think I see what's going on. Have you any gear configured on your Strava profile?

**Comment by robiningelbrecht** [comment]
@FoxxMD Please update to the latest version and re-import your data. Should be fixed

**Comment by FoxxMD** [comment]
I do not have any gear defined. After upgrading to 0.2.2 and re-running `import-data`, `build-files`  works now. Thanks
