### ISSUE TITLE
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 no such table: KeyValue

### ISSUE THREAD

**Issue by arminus** [dreeveapp/dreeve#52]
When running 
`docker compose exec strava-app bin/console app:strava:import-data`
(renamed my container the compose from app to strava-app)

I get
```
In ExceptionConverter.php line 52:
                                                                                                            
  An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 no such table: KeyValue  
                                                                                                           
In Exception.php line 28:
                                                             
  SQLSTATE[HY000]: General error: 1 no such table: KeyValue  
                                                             
In Connection.php line 59:
                                                             
  SQLSTATE[HY000]: General error: 1 no such table: KeyValue  
                                                             
app:strava:import-data
```
Based on https://github.com/robiningelbrecht/strava-statistics/issues/9 I've created an empty storage/database with 777 permission, after having run the command, I have a 0 byte strava.db owned by nobody:nogroup

Furthermore, I'm not quite sure how to set up a dev env (in this case to try make migrate-run), I'd rather run that inside a container and not have to install all the PHP dependencies (which actually?) natively on the host...

**Comment by robiningelbrecht** [comment]
@arminus you don't need to setup PHP dependencies at all? You can just use the docker-compose.yml example.
Everything is containerized

edit: is your issue fixed after creating `storage/database with 777 permission`?

**Comment by arminus** [comment]
> You can just use the docker-compose.yml example. Everything is containerized

for the runtime env, but I can't run make commands like that, can I? (I was just trying to get it to create the database since apparently it doesn't implicitly with the import command)

and no, the issue is not fixed, I created storage/database with 777 **before** doing anything

**Comment by robiningelbrecht** [comment]
@arminus The import command does manage the database explicitly:

```php
  $this->migrationRunner->run();
```

This line of code is executed right before importing data and creates the database

**Comment by arminus** [comment]
Well, in my case it doesn't:

```
ls -l storage/database
total 0
-rw-r--r-- 1 nobody nogroup 0 Dec 30 15:12 strava.db
```

**Comment by robiningelbrecht** [comment]
@arminus I think there's still a permission issue, can you run

```
docker compose exec app bin/console doctrine:migrations:migrate
```

Edit: also, based on your `ls -l` your file is not chmod'ed correctly I think?

**Comment by arminus** [comment]
Running `docker compose exec app bin/console doctrine:migrations:migrate` does create the strava.db now. Permissions and ownership same as above, so this is IMHO not a permission issue.

(I didn't create the file manually before since the dir permissions where 777 all along, so this is the container which creates it with those permissions.)

But I cannot confirm that this migration is being run implicitly, after the successful creation of it with the doctrine:migrations:migrate command, I shut down the container, deleted the file, restarted it and ran the import command again, same problem, clear repro of the issue in my environment.

So I do need an explicit `docker compose exec app bin/console doctrine:migrations:migrate` when starting from scratch.

**Comment by robiningelbrecht** [comment]
@arminus Unfortunately I cannot reproduce this. Not on my local, not on my self-hosted instance.

There's an open issue #37 where I need to look into the nobody thing.

**Comment by arminus** [comment]
I've changed the compose like so - but that shouldn't be a problem?
```
services:
  strava-app:
    image: robiningelbrecht/strava-statistics:latest
    container_name: strava-app
...
```

**Comment by robiningelbrecht** [comment]
@arminus no that should not be an issue at all.
I'm currently changing the docker image, would you be willing to test a specific version on your system to verify if the problem is fixed?

**Comment by arminus** [comment]
Sure

**Comment by robiningelbrecht** [comment]
@arminus Could you point your version to:

`robiningelbrecht/strava-statistics:ISSUE-37`

And let me know if that changes anything?

**Comment by arminus** [comment]
Same effect, here are my exact steps:
- copied docker-compose.yml and .env into a new/empty dir 
- renamed the service and container to strava-app-1 and changed the image to robiningelbrecht/strava-statistics:ISSUE-37
- docker compose up -d
- docker compose exec strava-app-1 bin/console app:strava:import-data
-> same error, db was not created
- sudo chmod -R 777 storage
- docker compose down and up again
- docker compose exec strava-app-1 bin/console app:strava:import-data
-> same error, 0 byte db now with owner sshd:input (as per my local passwd/group IDs)

**Comment by arminus** [comment]
Debian GNU/Linux 12 (bookworm)
Linux asterix 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux

**Comment by robiningelbrecht** [comment]
@arminus was able to reproduce this and found a major bug.
Could you try to set up again with version `robiningelbrecht/strava-statistics:ISSUE-37`?
The issue was fixed on my environment with this version

**Comment by arminus** [comment]
I'm afraid I see no difference (I did delete the old robiningelbrecht/strava-statistics:ISSUE-37 image and confirmed that the new image has a different sha256). Same error, 0 byte strava.db file.

**Comment by robiningelbrecht** [comment]
@arminus Not sure what to do here. You still get `SQLSTATE[HY000]: General error: 1 no such table: KeyValue`?

**Comment by arminus** [comment]
Yes. At any rate, I had a workaround with running the migration manually as you suggested above. What I could do is setup the required PHP stuff and try to trace/debug what's going on.

Which brings me to my question above: https://github.com/robiningelbrecht/strava-statistics?tab=readme-ov-file#-local-development is kind of thin - what are the preconditions for a dev env? PHP 8.4, what else? I might eventually also want to look at importing cross-country skiiing activities ... (but I'm not really fluent in PHP, we'll see)

**Comment by robiningelbrecht** [comment]
@arminus you can just clone the repo and use the docker-compose.yml in the root.

Run `make build-containers`

To install vendor packages, run:

`make composer arg="install"`

App should then be available on localhost:8081.

**Comment by arminus** [comment]
Ok, I'll give that a try. Probably next year, though ;-) Thanks so far!

**Comment by robiningelbrecht** [comment]
@arminus found the issue!! Releasing a fix

**Comment by robiningelbrecht** [comment]
@arminus Just released v0.2.4, can you update please?
99.9% sure this will fix the issue.

Earlier today I released a big new feature and introduced a bug, but only for people with new setups

**Comment by arminus** [comment]
empty dir, no storage/database present:

```
docker compose exec strava-app-1 bin/console app:strava:import-data

In DoctrineMigrationRunner.php line 17:
                                                                                                                                                                 
  In ExceptionConverter.php line 76:                                                                                                                             
                                                                                                                                                                 
    An exception occurred in the driver: SQLSTATE[HY000] [14] unable to open da                                                                                  
    tabase file                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                  
  In Exception.php line 28:                                                                                                                                      
                                                                                                                                                                 
    SQLSTATE[HY000] [14] unable to open database file                                                                                                            
                                                                                                                                                                                                                                                                                                                                  
  In Driver.php line 43:                                                                                                                                         
                                                                                                                                                                 
    SQLSTATE[HY000] [14] unable to open database file                                                                                                            
                                                                                                                                                                                                                                                                                                                                  
  doctrine:migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--no-all-or-noth  
  ing] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]                                                                                  
                                                                                                                                                                 
app:strava:import-data
```

=> still requires a `sudo chmod -R 777 storage` but after that, the import works so this is an improvement now :-)

permissions are now
```
ls -al storage/database
total 92
drwxrwxrwx 2 root   root     4096 Dec 30 18:41 .
drwxrwxrwx 4 root   root     4096 Dec 30 18:40 ..
-rw-r--r-- 1 nobody nogroup 86016 Dec 30 18:41 strava.db
```

**Comment by robiningelbrecht** [comment]
@arminus Yeah, the permissions I haven't figured out yet. I was referring to the nasty database error :)
Ok If I open a new issue for that one and tag you in it? I'll try to make a new PR tomorrow so you can test again, because I don't have this permission issue. Are you up for that?

**Comment by arminus** [comment]
> Ok If I open a new issue for that one and tag you in it?

Sure.
